#!/usr/bin/env python
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Copyright (C) 2013 Luca Filipozzi <lfilipoz@debian.org>

import argparse
from email.mime.text import MIMEText
import sys

parser = argparse.ArgumentParser()
parser.add_argument('recipient')
parser.add_argument('-s', '--subject')
args = parser.parse_args()

msg = MIMEText(sys.stdin.read())
msg['Subject'] = args.subject
msg['From'] = 'Luca Filipozzi <lfilipoz@debian.org>'
msg['Reply-To'] = 'Luca Filipozzi <lfilipoz@emyr.net>'
msg['To'] = args.recipient

print msg.as_string()

# vim: set ts=4 sw=4 et si:
