#!/usr/bin/env python
import os
import sys
from django.core.management import execute_manager
from ud import settings
sys.path.append(os.path.dirname(os.path.realpath(settings.__file__)))
execute_manager(settings)
